name: year4 CI

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to Bitbucket
        env:
          BITBUCKET_USERNAME: ${{ secrets.BITBUCKET_USERNAME }}
          BITBUCKET_APP_PASSWORD: ${{ secrets.BITBUCKET_APP_PASSWORD }}
        run: |
          git config bogdan@atodorow.com xgtwdr007yolcsu6a102oa2bi696sp@bots.bitbucket.org
          git remote add bitbucket https://bitbucket.org/${{ env.BITBUCKET_USERNAME }}/year-4.git
          git push bitbucket --all --force